version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: hire-a-driver-zookeeper
    ports:
      - "2181:2181" # Map Zookeeper's default port to the host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 # Zookeeper client port
      ZOOKEEPER_TICK_TIME: 2000  # Zookeeper tick time (default is 2000ms)
  redis:
    image: redis:latest
    container_name: hire-a-driver-redis
    ports:
      - "6379:6379" # Map port 6379 on the host to port 6379 in the container
    restart: unless-stopped
  postgres:
    container_name: hire-a-driver-postgresql
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: hide
      POSTGRES_PASSWORD: hide
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: